2020-04-20 17:42:48,628 ERROR: Exception on /login [GET] [in c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\engin\Documents\projects\python-exercises\microblog\app\routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: login.html
2020-04-20 17:42:53,493 ERROR: Exception on /favicon.ico [GET] [in c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "C:\Users\engin\Documents\projects\python-exercises\microblog\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: 404.html
2020-04-20 17:43:51,658 INFO: Microblog startup [in C:\Users\engin\Documents\projects\python-exercises\microblog\app\__init__.py:49]
2020-04-20 17:44:18,456 INFO: Microblog startup [in C:\Users\engin\Documents\projects\python-exercises\microblog\app\__init__.py:49]
2020-04-20 17:47:28,903 INFO: Microblog startup [in C:\Users\engin\Documents\projects\python-exercises\microblog\app\__init__.py:50]
2020-04-20 17:47:36,280 ERROR: Exception on /login [GET] [in c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\engin\Documents\projects\python-exercises\microblog\app\routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\engin\documents\projects\python-exercises\microblog\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: login.html
2020-04-20 17:48:02,668 INFO: Microblog startup [in C:\Users\engin\Documents\projects\python-exercises\microblog\app\__init__.py:50]
